Ext.define('XMLifeOperating.store.Navigation', {
    extend: 'Ext.data.TreeStore',
    model : 'XMLifeOperating.model.Navigation',
    proxy : new XMLifeOperating.generic.BaseProxy('module/getUserModulesTree'),  
    defaultRootId : '',
    autoSync: false,
    autoLoad: false,
    root: {
    	expanded: false,
    	children: [
		    // {
		    //     "id": "shoplist",
		    //     "text": "店铺管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "shoplist",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "delivererZoneList",
		    //     "text": "线路管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "delivererZoneList",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "shopTopShopsList",
		    //     "text": "首页配置",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "shopTopShopsList",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "homePage",
		    //     "text": "主页配置",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "homePage",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "ShopConfigManage",
		    //     "text": "店铺配置",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "ShopConfigManage",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "residentaldistrictlist",
		    //     "text": "配送地址管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "residentaldistrictlist",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "operateManage",
		    //     "text": "操作管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": false,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [
		    //         {
		    //             "id": "dealShopAreaList",
		    //             "text": "货到中心管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.dealShopAreaList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "dealProblemDealsList",
		    //             "text": "问题订单管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.dealProblemDealsList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "dealwaitassignshopperlist",
		    //             "text": "今日未分配买手订单",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.dealwaitassignshopperlist",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "dealWaitAssignDelivererList",
		    //             "text": "今日未分配配送订单",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.dealWaitAssignDelivererList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "dealCashOnDeliveryList",
		    //             "text": "货到付款管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.dealCashOnDeliveryList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "capacity",
		    //             "text": "中心运力配置",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "operateManage.capacity",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         }
		    //     ],
		    //     "uniqueName": "operateManage",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "staffManage",
		    //     "text": "员工管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": false,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [
		    //         {
		    //             "id": "shopperList",
		    //             "text": "买手管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "staffManage.shopperList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "delivererList",
		    //             "text": "配送员管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "staffManage.delivererList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         }
		    //     ],
		    //     "uniqueName": "staffManage",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "customerManage",
		    //     "text": "用户管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": false,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [
		    //         {
		    //             "id": "customerList",
		    //             "text": "用户信息管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "customerManage.customerList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         },
		    //         {
		    //             "id": "feedbackList",
		    //             "text": "用户反馈管理",
		    //             "platFormName": "Area",
		    //             "platFormType": 2,
		    //             "leaf": true,
		    //             "isAuth": false,
		    //             "notShow": false,
		    //             "children": [],
		    //             "uniqueName": "customerManage.feedbackList",
		    //             "inheritLevel": 0,
		    //             "auth": false
		    //         }
		    //     ],
		    //     "uniqueName": "customerManage",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "dealList",
		    //     "text": "订单管理",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "dealList",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // },
		    // {
		    //     "id": "RefundList",
		    //     "text": "退款查询",
		    //     "platFormName": "Area",
		    //     "platFormType": 2,
		    //     "leaf": true,
		    //     "isAuth": false,
		    //     "notShow": false,
		    //     "children": [],
		    //     "uniqueName": "RefundList",
		    //     "inheritLevel": 0,
		    //     "auth": false
		    // }
		]
    }
});