Ext.define('XMLifeOperating.model.DealProblemDeals', {
    extend: 'Ext.data.Model',
    fields: [
        'id',
        'created',
        'taskId',
        'dealBackendId',
        'zoneName',
        'dtoAddress',
        'status',
        'problem',
        'customerName',
        'customerPhone',
        'shopAreaName',
        'shopperNames',
        'superShopperName',
        'shopNames',
        'delivererName',
        'created',
        'deliverTime',
        'remainTime',
        'assignSuperShopperTime',
        'taskDone',
        'beginDeliverTime',
        'completeTime',
        'shortId',
        'contactsName',
        'contactsPhone',
        'customId'
    ],
    proxy: new XMLifeOperating.generic.BaseProxy('deal/problemDeals')
});
