var dataProxy = new XMLifeOperating.generic.BaseProxy('shop');
Ext.define('XMLifeOperating.model.Shop', {
	extend: 'Ext.data.Model',
	fields: [
		'id',
		'name',
		'templateId',
		'templateName',
		'desc',
		'openTime',
		'closeTime',
		'openTimeText',
		'closeTimeText',
		'lng',
		'lat',
		'url',
		'city',
		'areaNames',
		'banners',
		'address',
		'time',
		'areaIds',
		'shopBannerTemplateId',
		'shopperCount',
		'shopId',
		'status',
		'areas',
		'beCopyedShopId',
		'autoOnline'
	],
	idProperty: 'id',
	proxy: dataProxy,
});